on:
  push:

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "Test ${{ github.event_name }}"
